May 21 22:52:52 worker1 k3s[1837]: E0521 22:52:52.917883    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-mesh,Image:ghcr.io/chaos-mesh/chaos-mesh:v2.7.2,Command:[/usr/local/bin/chaos-controller-manager],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:webhook,HostPort:0,ContainerPort:10250,Protocol:TCP,HostIP:,},ContainerPort{Name:http,HostPort:0,ContainerPort:10080,Protocol:TCP,HostIP:,},ContainerPort{Name:pprof,HostPort:0,ContainerPort:10081,Protocol:TCP,HostIP:,},ContainerPort{Name:ctrl,HostPort:0,ContainerPort:10082,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:METRICS_PORT,Value:10080,ValueFrom:nil,},EnvVar{Name:WEBHOOK_PORT,Value:10250,ValueFrom:nil,},EnvVar{Name:NAMESPACE,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:TEMPLATE_NAMESPACE,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:ALLOW_HOST_NETWORK_TESTING,Value:false,ValueFrom:nil,},EnvVar{Name:TARGET_NAMESPACE,Value:chaos-mesh,ValueFrom:nil,},EnvVar{Name:CLUSTER_SCOPED,Value:true,ValueFrom:nil,},EnvVar{Name:TZ,Value:UTC,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_SERVICE_PORT,Value:31767,ValueFrom:nil,},EnvVar{Name:BPFKI_PORT,Value:50051,ValueFrom:nil,},EnvVar{Name:ENABLED_CONTROLLERS,Value:*,ValueFrom:nil,},EnvVar{Name:ENABLED_WEBHOOKS,Value:*,ValueFrom:nil,},EnvVar{Name:TEMPLATE_LABELS,Value:app.kubernetes.io/component:template,ValueFrom:nil,},EnvVar{Name:CONFIGMAP_LABELS,Value:app.kubernetes.io/component:webhook,ValueFrom:nil,},EnvVar{Name:ENABLE_FILTER_NAMESPACE,Value:false,ValueFrom:nil,},EnvVar{Name:PPROF_ADDR,Value::10081,ValueFrom:nil,},EnvVar{Name:CTRL_ADDR,Value::10082,ValueFrom:nil,},EnvVar{Name:CHAOS_DNS_SERVICE_NAME,Value:chaos-mesh-dns-server,ValueFrom:nil,},EnvVar{Name:CHAOS_DNS_SERVICE_PORT,Value:9288,ValueFrom:nil,},EnvVar{Name:SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:CHAOSD_SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_CLIENT_CERT,Value:/etc/chaos-daemon/cert/tls.crt,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_CLIENT_KEY,Value:/etc/chaos-daemon/cert/tls.key,ValueFrom:nil,},EnvVar{Name:CHAOS_MESH_CA_CERT,Value:/etc/chaos-daemon/cert/ca.crt,ValueFrom:nil,},EnvVar{Name:QPS,Value:30,ValueFrom:nil,},EnvVar{Name:BURST,Value:50,ValueFrom:nil,},EnvVar{Name:CHAOSD_CA_CERT,Value:/etc/chaosd/cert/ca.crt,ValueFrom:nil,},EnvVar{Name:CHAOSD_CLIENT_CERT,Value:/etc/chaosd/cert/tls.crt,ValueFrom:nil,},EnvVar{Name:CHAOSD_CLIENT_KEY,Value:/etc/chaosd/cert/tls.key,ValueFrom:nil,},EnvVar{Name:POD_FAILURE_PAUSE_IMAGE,Value:gcr.io/google-containers/pause:latest,ValueFrom:nil,},EnvVar{Name:ENABLE_LEADER_ELECTION,Value:true,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_LEASE_DURATION,Value:15s,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_RENEW_DEADLINE,Value:10s,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_RETRY_PERIOD,Value:2s,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{25 -3} {<nil>} 25m DecimalSI},memory: {{268435456 0} {<nil>}  BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:webhook-certs,ReadOnly:true,MountPath:/etc/webhook/certs,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:chaos-daemon-client-cert,ReadOnly:true,MountPath:/etc/chaos-daemon/cert,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:chaosd-client-cert,ReadOnly:true,MountPath:/etc/chaosd/cert,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-d4qwp,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-controller-manager-7477fb8fd9-b74v7_chaos-mesh(bc557036-fe8f-485d-9179-70bda03cb825): ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\": dial tcp 140.82.112.34:443: i/o timeout"
May 21 22:52:52 worker1 k3s[1837]: E0521 22:52:52.919469    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ErrImagePull: \"rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:52:52 worker1 k3s[1837]: E0521 22:52:52.922308    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.112.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2"
May 21 22:52:52 worker1 k3s[1837]: E0521 22:52:52.922371    1837 kuberuntime_image.go:55] "Failed to pull image" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.112.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2"
May 21 22:52:52 worker1 k3s[1837]: E0521 22:52:52.922558    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-dashboard,Image:ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2,Command:[/usr/local/bin/chaos-dashboard],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:http,HostPort:0,ContainerPort:2333,Protocol:TCP,HostIP:,},ContainerPort{Name:metric,HostPort:0,ContainerPort:2334,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:CLEAN_SYNC_PERIOD,Value:12h,ValueFrom:nil,},EnvVar{Name:DATABASE_DATASOURCE,Value:/data/core.sqlite,ValueFrom:nil,},EnvVar{Name:DATABASE_DRIVER,Value:sqlite3,ValueFrom:nil,},EnvVar{Name:LISTEN_HOST,Value:0.0.0.0,ValueFrom:nil,},EnvVar{Name:LISTEN_PORT,Value:2333,ValueFrom:nil,},EnvVar{Name:METRIC_HOST,Value:0.0.0.0,ValueFrom:nil,},EnvVar{Name:METRIC_PORT,Value:2334,ValueFrom:nil,},EnvVar{Name:TTL_EVENT,Value:168h,ValueFrom:nil,},EnvVar{Name:TTL_EXPERIMENT,Value:336h,ValueFrom:nil,},EnvVar{Name:TTL_SCHEDULE,Value:336h,ValueFrom:nil,},EnvVar{Name:TTL_WORKFLOW,Value:336h,ValueFrom:nil,},EnvVar{Name:TZ,Value:UTC,ValueFrom:nil,},EnvVar{Name:CLUSTER_SCOPED,Value:true,ValueFrom:nil,},EnvVar{Name:TARGET_NAMESPACE,Value:chaos-mesh,ValueFrom:nil,},EnvVar{Name:ENABLE_FILTER_NAMESPACE,Value:false,ValueFrom:nil,},EnvVar{Name:SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:GCP_SECURITY_MODE,Value:false,ValueFrom:nil,},EnvVar{Name:GCP_CLIENT_ID,Value:,ValueFrom:nil,},EnvVar{Name:GCP_CLIENT_SECRET,Value:,ValueFrom:nil,},EnvVar{Name:DNS_SERVER_CREATE,Value:true,ValueFrom:nil,},EnvVar{Name:ROOT_URL,Value:http://localhost:2333,ValueFrom:nil,},EnvVar{Name:ENABLE_PROFILING,Value:true,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{25 -3} {<nil>} 25m DecimalSI},memory: {{268435456 0} {<nil>}  BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:storage-volume,ReadOnly:false,MountPath:/data,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-k4f2p,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-dashboard-5966b8f56b-m5tv9_chaos-mesh(7555d7bf-e3fd-4c73-8924-5ee983382545): ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.112.34:443: i/o timeout"
May 21 22:52:52 worker1 k3s[1837]: E0521 22:52:52.923879    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ErrImagePull: \"rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:52:54 worker1 k3s[1837]: E0521 22:52:54.913872    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:52:59 worker1 k3s[1837]: E0521 22:52:59.915814    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:53:06 worker1 k3s[1837]: E0521 22:53:06.927860    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:53:07 worker1 k3s[1837]: E0521 22:53:07.907425    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:53:07 worker1 k3s[1837]: E0521 22:53:07.914165    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:53:10 worker1 k3s[1837]: E0521 22:53:10.914247    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:53:18 worker1 k3s[1837]: E0521 22:53:18.918802    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:53:20 worker1 k3s[1837]: E0521 22:53:20.968805    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:53:21 worker1 k3s[1837]: E0521 22:53:21.924207    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:53:24 worker1 k3s[1837]: E0521 22:53:24.924493    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:53:33 worker1 k3s[1837]: E0521 22:53:33.902000    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:53:34 worker1 k3s[1837]: E0521 22:53:34.933027    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:53:35 worker1 k3s[1837]: E0521 22:53:35.918745    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:53:39 worker1 k3s[1837]: E0521 22:53:39.939157    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:53:47 worker1 k3s[1837]: E0521 22:53:47.904099    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:53:47 worker1 k3s[1837]: E0521 22:53:47.908452    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:53:48 worker1 k3s[1837]: E0521 22:53:48.897009    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:53:54 worker1 k3s[1837]: E0521 22:53:54.894833    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:53:59 worker1 k3s[1837]: E0521 22:53:59.903972    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:54:01 worker1 k3s[1837]: E0521 22:54:01.966046    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:54:03 worker1 k3s[1837]: E0521 22:54:03.910100    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.112.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:54:39 worker1 k3s[1837]: E0521 22:54:39.968699    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-daemon:v2.7.2"
May 21 22:54:39 worker1 k3s[1837]: E0521 22:54:39.968846    1837 kuberuntime_image.go:55] "Failed to pull image" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-daemon:v2.7.2"
May 21 22:54:39 worker1 k3s[1837]: E0521 22:54:39.969141    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-daemon,Image:ghcr.io/chaos-mesh/chaos-daemon:v2.7.2,Command:[/usr/local/bin/chaos-daemon --runtime containerd --http-port 31766 --grpc-port 31767 --pprof --ca /etc/chaos-daemon/cert/ca.crt --cert /etc/chaos-daemon/cert/tls.crt --key /etc/chaos-daemon/cert/tls.key --runtime-socket-path /host-run/containerd.sock],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:grpc,HostPort:0,ContainerPort:31767,Protocol:TCP,HostIP:,},ContainerPort{Name:http,HostPort:0,ContainerPort:31766,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:TZ,Value:UTC,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:socket-path,ReadOnly:false,MountPath:/host-run,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:sys-path,ReadOnly:false,MountPath:/host-sys,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:lib-modules,ReadOnly:false,MountPath:/lib/modules,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:chaos-daemon-cert,ReadOnly:true,MountPath:/etc/chaos-daemon/cert,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-c4bv2,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[SYS_PTRACE],Drop:[],},Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,AppArmorProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-daemon-ggxh4_chaos-mesh(a6f6f570-127b-49d7-879f-f0cfddc113b1): ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout"
May 21 22:54:39 worker1 k3s[1837]: E0521 22:54:39.971284    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ErrImagePull: \"rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:54:43 worker1 k3s[1837]: E0521 22:54:43.933873    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\": dial tcp 140.82.113.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-coredns:v0.2.6"
May 21 22:54:43 worker1 k3s[1837]: E0521 22:54:43.934009    1837 kuberuntime_image.go:55] "Failed to pull image" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\": dial tcp 140.82.113.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-coredns:v0.2.6"
May 21 22:54:43 worker1 k3s[1837]: E0521 22:54:43.934354    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-dns-server,Image:ghcr.io/chaos-mesh/chaos-coredns:v0.2.6,Command:[],Args:[-conf /etc/chaos-dns/Corefile],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:dns,HostPort:0,ContainerPort:5353,Protocol:UDP,HostIP:,},ContainerPort{Name:dns-tcp,HostPort:0,ContainerPort:5353,Protocol:TCP,HostIP:,},ContainerPort{Name:metrics,HostPort:0,ContainerPort:9153,Protocol:TCP,HostIP:,},ContainerPort{Name:grpc,HostPort:0,ContainerPort:9288,Protocol:TCP,HostIP:,},},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{73400320 0} {<nil>} 70Mi BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:config-volume,ReadOnly:true,MountPath:/etc/chaos-dns,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-jzkm8,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:{0 8080 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:5,TerminationGracePeriodSeconds:nil,},ReadinessProbe:&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/ready,Port:{0 8181 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,},Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[NET_BIND_SERVICE],Drop:[all],},Privileged:nil,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:*true,AllowPrivilegeEscalation:*false,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,AppArmorProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-dns-server-558955948b-9pnq4_chaos-mesh(bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887): ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\": dial tcp 140.82.113.34:443: i/o timeout"
May 21 22:54:43 worker1 k3s[1837]: E0521 22:54:43.936241    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ErrImagePull: \"rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:54:45 worker1 k3s[1837]: E0521 22:54:45.953955    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2"
May 21 22:54:45 worker1 k3s[1837]: E0521 22:54:45.954023    1837 kuberuntime_image.go:55] "Failed to pull image" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2"
May 21 22:54:45 worker1 k3s[1837]: E0521 22:54:45.954361    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-dashboard,Image:ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2,Command:[/usr/local/bin/chaos-dashboard],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:http,HostPort:0,ContainerPort:2333,Protocol:TCP,HostIP:,},ContainerPort{Name:metric,HostPort:0,ContainerPort:2334,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:CLEAN_SYNC_PERIOD,Value:12h,ValueFrom:nil,},EnvVar{Name:DATABASE_DATASOURCE,Value:/data/core.sqlite,ValueFrom:nil,},EnvVar{Name:DATABASE_DRIVER,Value:sqlite3,ValueFrom:nil,},EnvVar{Name:LISTEN_HOST,Value:0.0.0.0,ValueFrom:nil,},EnvVar{Name:LISTEN_PORT,Value:2333,ValueFrom:nil,},EnvVar{Name:METRIC_HOST,Value:0.0.0.0,ValueFrom:nil,},EnvVar{Name:METRIC_PORT,Value:2334,ValueFrom:nil,},EnvVar{Name:TTL_EVENT,Value:168h,ValueFrom:nil,},EnvVar{Name:TTL_EXPERIMENT,Value:336h,ValueFrom:nil,},EnvVar{Name:TTL_SCHEDULE,Value:336h,ValueFrom:nil,},EnvVar{Name:TTL_WORKFLOW,Value:336h,ValueFrom:nil,},EnvVar{Name:TZ,Value:UTC,ValueFrom:nil,},EnvVar{Name:CLUSTER_SCOPED,Value:true,ValueFrom:nil,},EnvVar{Name:TARGET_NAMESPACE,Value:chaos-mesh,ValueFrom:nil,},EnvVar{Name:ENABLE_FILTER_NAMESPACE,Value:false,ValueFrom:nil,},EnvVar{Name:SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:GCP_SECURITY_MODE,Value:false,ValueFrom:nil,},EnvVar{Name:GCP_CLIENT_ID,Value:,ValueFrom:nil,},EnvVar{Name:GCP_CLIENT_SECRET,Value:,ValueFrom:nil,},EnvVar{Name:DNS_SERVER_CREATE,Value:true,ValueFrom:nil,},EnvVar{Name:ROOT_URL,Value:http://localhost:2333,ValueFrom:nil,},EnvVar{Name:ENABLE_PROFILING,Value:true,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{25 -3} {<nil>} 25m DecimalSI},memory: {{268435456 0} {<nil>}  BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:storage-volume,ReadOnly:false,MountPath:/data,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-k4f2p,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-dashboard-5966b8f56b-m5tv9_chaos-mesh(7555d7bf-e3fd-4c73-8924-5ee983382545): ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout"
May 21 22:54:45 worker1 k3s[1837]: E0521 22:54:45.956481    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ErrImagePull: \"rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:54:45 worker1 k3s[1837]: E0521 22:54:45.957211    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-mesh:v2.7.2"
May 21 22:54:45 worker1 k3s[1837]: E0521 22:54:45.957269    1837 kuberuntime_image.go:55] "Failed to pull image" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-mesh:v2.7.2"
May 21 22:54:45 worker1 k3s[1837]: E0521 22:54:45.957524    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-mesh,Image:ghcr.io/chaos-mesh/chaos-mesh:v2.7.2,Command:[/usr/local/bin/chaos-controller-manager],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:webhook,HostPort:0,ContainerPort:10250,Protocol:TCP,HostIP:,},ContainerPort{Name:http,HostPort:0,ContainerPort:10080,Protocol:TCP,HostIP:,},ContainerPort{Name:pprof,HostPort:0,ContainerPort:10081,Protocol:TCP,HostIP:,},ContainerPort{Name:ctrl,HostPort:0,ContainerPort:10082,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:METRICS_PORT,Value:10080,ValueFrom:nil,},EnvVar{Name:WEBHOOK_PORT,Value:10250,ValueFrom:nil,},EnvVar{Name:NAMESPACE,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:TEMPLATE_NAMESPACE,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:ALLOW_HOST_NETWORK_TESTING,Value:false,ValueFrom:nil,},EnvVar{Name:TARGET_NAMESPACE,Value:chaos-mesh,ValueFrom:nil,},EnvVar{Name:CLUSTER_SCOPED,Value:true,ValueFrom:nil,},EnvVar{Name:TZ,Value:UTC,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_SERVICE_PORT,Value:31767,ValueFrom:nil,},EnvVar{Name:BPFKI_PORT,Value:50051,ValueFrom:nil,},EnvVar{Name:ENABLED_CONTROLLERS,Value:*,ValueFrom:nil,},EnvVar{Name:ENABLED_WEBHOOKS,Value:*,ValueFrom:nil,},EnvVar{Name:TEMPLATE_LABELS,Value:app.kubernetes.io/component:template,ValueFrom:nil,},EnvVar{Name:CONFIGMAP_LABELS,Value:app.kubernetes.io/component:webhook,ValueFrom:nil,},EnvVar{Name:ENABLE_FILTER_NAMESPACE,Value:false,ValueFrom:nil,},EnvVar{Name:PPROF_ADDR,Value::10081,ValueFrom:nil,},EnvVar{Name:CTRL_ADDR,Value::10082,ValueFrom:nil,},EnvVar{Name:CHAOS_DNS_SERVICE_NAME,Value:chaos-mesh-dns-server,ValueFrom:nil,},EnvVar{Name:CHAOS_DNS_SERVICE_PORT,Value:9288,ValueFrom:nil,},EnvVar{Name:SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:CHAOSD_SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_CLIENT_CERT,Value:/etc/chaos-daemon/cert/tls.crt,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_CLIENT_KEY,Value:/etc/chaos-daemon/cert/tls.key,ValueFrom:nil,},EnvVar{Name:CHAOS_MESH_CA_CERT,Value:/etc/chaos-daemon/cert/ca.crt,ValueFrom:nil,},EnvVar{Name:QPS,Value:30,ValueFrom:nil,},EnvVar{Name:BURST,Value:50,ValueFrom:nil,},EnvVar{Name:CHAOSD_CA_CERT,Value:/etc/chaosd/cert/ca.crt,ValueFrom:nil,},EnvVar{Name:CHAOSD_CLIENT_CERT,Value:/etc/chaosd/cert/tls.crt,ValueFrom:nil,},EnvVar{Name:CHAOSD_CLIENT_KEY,Value:/etc/chaosd/cert/tls.key,ValueFrom:nil,},EnvVar{Name:POD_FAILURE_PAUSE_IMAGE,Value:gcr.io/google-containers/pause:latest,ValueFrom:nil,},EnvVar{Name:ENABLE_LEADER_ELECTION,Value:true,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_LEASE_DURATION,Value:15s,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_RENEW_DEADLINE,Value:10s,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_RETRY_PERIOD,Value:2s,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{25 -3} {<nil>} 25m DecimalSI},memory: {{268435456 0} {<nil>}  BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:webhook-certs,ReadOnly:true,MountPath:/etc/webhook/certs,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:chaos-daemon-client-cert,ReadOnly:true,MountPath:/etc/chaos-daemon/cert,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:chaosd-client-cert,ReadOnly:true,MountPath:/etc/chaosd/cert,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-d4qwp,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-controller-manager-7477fb8fd9-b74v7_chaos-mesh(bc557036-fe8f-485d-9179-70bda03cb825): ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\": dial tcp 140.82.113.34:443: i/o timeout"
May 21 22:54:45 worker1 k3s[1837]: E0521 22:54:45.958796    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ErrImagePull: \"rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:54:52 worker1 k3s[1837]: E0521 22:54:52.900912    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:54:54 worker1 k3s[1837]: E0521 22:54:54.937886    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:54:56 worker1 k3s[1837]: E0521 22:54:56.926511    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:54:57 worker1 k3s[1837]: E0521 22:54:57.909358    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:55:04 worker1 k3s[1837]: E0521 22:55:04.908462    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:55:08 worker1 k3s[1837]: E0521 22:55:08.910196    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:55:11 worker1 k3s[1837]: E0521 22:55:11.912651    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:55:12 worker1 k3s[1837]: E0521 22:55:12.902013    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:55:18 worker1 k3s[1837]: E0521 22:55:18.917556    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:55:19 worker1 k3s[1837]: E0521 22:55:19.903534    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:55:23 worker1 k3s[1837]: E0521 22:55:23.902415    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:55:26 worker1 k3s[1837]: E0521 22:55:26.898250    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:55:29 worker1 k3s[1837]: E0521 22:55:29.921543    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:55:30 worker1 k3s[1837]: E0521 22:55:30.901216    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:55:34 worker1 k3s[1837]: E0521 22:55:34.932054    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:55:39 worker1 k3s[1837]: E0521 22:55:39.910853    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:55:42 worker1 k3s[1837]: E0521 22:55:42.936732    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:55:43 worker1 k3s[1837]: E0521 22:55:43.919089    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:55:48 worker1 k3s[1837]: E0521 22:55:48.915349    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:55:53 worker1 k3s[1837]: E0521 22:55:53.910573    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:55:54 worker1 k3s[1837]: E0521 22:55:54.924463    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:55:55 worker1 k3s[1837]: E0521 22:55:55.949844    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:56:02 worker1 k3s[1837]: E0521 22:56:02.903977    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:56:06 worker1 k3s[1837]: E0521 22:56:06.919177    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:56:07 worker1 k3s[1837]: E0521 22:56:07.899814    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:56:11 worker1 k3s[1837]: E0521 22:56:11.907668    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:56:16 worker1 k3s[1837]: E0521 22:56:16.910519    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:56:19 worker1 k3s[1837]: E0521 22:56:19.910413    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:56:20 worker1 k3s[1837]: E0521 22:56:20.918277    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:56:22 worker1 k3s[1837]: E0521 22:56:22.919366    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:56:30 worker1 k3s[1837]: E0521 22:56:30.912014    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:56:31 worker1 k3s[1837]: E0521 22:56:31.911871    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:56:33 worker1 k3s[1837]: E0521 22:56:33.896502    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:56:37 worker1 k3s[1837]: E0521 22:56:37.905534    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:56:41 worker1 k3s[1837]: E0521 22:56:41.922293    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:56:43 worker1 k3s[1837]: E0521 22:56:43.906635    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:56:48 worker1 k3s[1837]: E0521 22:56:48.897634    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:56:50 worker1 k3s[1837]: E0521 22:56:50.922564    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:56:56 worker1 k3s[1837]: E0521 22:56:56.919784    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:56:56 worker1 k3s[1837]: E0521 22:56:56.920680    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:57:00 worker1 k3s[1837]: E0521 22:57:00.900216    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:57:04 worker1 k3s[1837]: E0521 22:57:04.897404    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:57:07 worker1 k3s[1837]: E0521 22:57:07.903233    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:57:07 worker1 k3s[1837]: E0521 22:57:07.903498    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:57:13 worker1 k3s[1837]: E0521 22:57:13.897283    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:57:18 worker1 k3s[1837]: E0521 22:57:18.926201    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:57:19 worker1 k3s[1837]: E0521 22:57:19.904215    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:57:20 worker1 k3s[1837]: E0521 22:57:20.904455    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:57:24 worker1 k3s[1837]: E0521 22:57:24.901837    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.113.34:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:58:02 worker1 k3s[1837]: E0521 22:58:02.953103    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-mesh:v2.7.2"
May 21 22:58:02 worker1 k3s[1837]: E0521 22:58:02.953517    1837 kuberuntime_image.go:55] "Failed to pull image" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-mesh:v2.7.2"
May 21 22:58:02 worker1 k3s[1837]: E0521 22:58:02.954923    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-mesh,Image:ghcr.io/chaos-mesh/chaos-mesh:v2.7.2,Command:[/usr/local/bin/chaos-controller-manager],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:webhook,HostPort:0,ContainerPort:10250,Protocol:TCP,HostIP:,},ContainerPort{Name:http,HostPort:0,ContainerPort:10080,Protocol:TCP,HostIP:,},ContainerPort{Name:pprof,HostPort:0,ContainerPort:10081,Protocol:TCP,HostIP:,},ContainerPort{Name:ctrl,HostPort:0,ContainerPort:10082,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:METRICS_PORT,Value:10080,ValueFrom:nil,},EnvVar{Name:WEBHOOK_PORT,Value:10250,ValueFrom:nil,},EnvVar{Name:NAMESPACE,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:TEMPLATE_NAMESPACE,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:ALLOW_HOST_NETWORK_TESTING,Value:false,ValueFrom:nil,},EnvVar{Name:TARGET_NAMESPACE,Value:chaos-mesh,ValueFrom:nil,},EnvVar{Name:CLUSTER_SCOPED,Value:true,ValueFrom:nil,},EnvVar{Name:TZ,Value:UTC,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_SERVICE_PORT,Value:31767,ValueFrom:nil,},EnvVar{Name:BPFKI_PORT,Value:50051,ValueFrom:nil,},EnvVar{Name:ENABLED_CONTROLLERS,Value:*,ValueFrom:nil,},EnvVar{Name:ENABLED_WEBHOOKS,Value:*,ValueFrom:nil,},EnvVar{Name:TEMPLATE_LABELS,Value:app.kubernetes.io/component:template,ValueFrom:nil,},EnvVar{Name:CONFIGMAP_LABELS,Value:app.kubernetes.io/component:webhook,ValueFrom:nil,},EnvVar{Name:ENABLE_FILTER_NAMESPACE,Value:false,ValueFrom:nil,},EnvVar{Name:PPROF_ADDR,Value::10081,ValueFrom:nil,},EnvVar{Name:CTRL_ADDR,Value::10082,ValueFrom:nil,},EnvVar{Name:CHAOS_DNS_SERVICE_NAME,Value:chaos-mesh-dns-server,ValueFrom:nil,},EnvVar{Name:CHAOS_DNS_SERVICE_PORT,Value:9288,ValueFrom:nil,},EnvVar{Name:SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:CHAOSD_SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_CLIENT_CERT,Value:/etc/chaos-daemon/cert/tls.crt,ValueFrom:nil,},EnvVar{Name:CHAOS_DAEMON_CLIENT_KEY,Value:/etc/chaos-daemon/cert/tls.key,ValueFrom:nil,},EnvVar{Name:CHAOS_MESH_CA_CERT,Value:/etc/chaos-daemon/cert/ca.crt,ValueFrom:nil,},EnvVar{Name:QPS,Value:30,ValueFrom:nil,},EnvVar{Name:BURST,Value:50,ValueFrom:nil,},EnvVar{Name:CHAOSD_CA_CERT,Value:/etc/chaosd/cert/ca.crt,ValueFrom:nil,},EnvVar{Name:CHAOSD_CLIENT_CERT,Value:/etc/chaosd/cert/tls.crt,ValueFrom:nil,},EnvVar{Name:CHAOSD_CLIENT_KEY,Value:/etc/chaosd/cert/tls.key,ValueFrom:nil,},EnvVar{Name:POD_FAILURE_PAUSE_IMAGE,Value:gcr.io/google-containers/pause:latest,ValueFrom:nil,},EnvVar{Name:ENABLE_LEADER_ELECTION,Value:true,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_LEASE_DURATION,Value:15s,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_RENEW_DEADLINE,Value:10s,ValueFrom:nil,},EnvVar{Name:LEADER_ELECT_RETRY_PERIOD,Value:2s,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{25 -3} {<nil>} 25m DecimalSI},memory: {{268435456 0} {<nil>}  BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:webhook-certs,ReadOnly:true,MountPath:/etc/webhook/certs,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:chaos-daemon-client-cert,ReadOnly:true,MountPath:/etc/chaos-daemon/cert,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:chaosd-client-cert,ReadOnly:true,MountPath:/etc/chaosd/cert,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-d4qwp,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-controller-manager-7477fb8fd9-b74v7_chaos-mesh(bc557036-fe8f-485d-9179-70bda03cb825): ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout"
May 21 22:58:02 worker1 k3s[1837]: E0521 22:58:02.956391    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ErrImagePull: \"rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:58:03 worker1 k3s[1837]: E0521 22:58:03.916820    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-daemon:v2.7.2"
May 21 22:58:03 worker1 k3s[1837]: E0521 22:58:03.916887    1837 kuberuntime_image.go:55] "Failed to pull image" err="failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-daemon:v2.7.2"
May 21 22:58:03 worker1 k3s[1837]: E0521 22:58:03.917107    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-daemon,Image:ghcr.io/chaos-mesh/chaos-daemon:v2.7.2,Command:[/usr/local/bin/chaos-daemon --runtime containerd --http-port 31766 --grpc-port 31767 --pprof --ca /etc/chaos-daemon/cert/ca.crt --cert /etc/chaos-daemon/cert/tls.crt --key /etc/chaos-daemon/cert/tls.key --runtime-socket-path /host-run/containerd.sock],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:grpc,HostPort:0,ContainerPort:31767,Protocol:TCP,HostIP:,},ContainerPort{Name:http,HostPort:0,ContainerPort:31766,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:TZ,Value:UTC,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:socket-path,ReadOnly:false,MountPath:/host-run,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:sys-path,ReadOnly:false,MountPath:/host-sys,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:lib-modules,ReadOnly:false,MountPath:/lib/modules,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:chaos-daemon-cert,ReadOnly:true,MountPath:/etc/chaos-daemon/cert,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-c4bv2,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[SYS_PTRACE],Drop:[],},Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,AppArmorProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-daemon-ggxh4_chaos-mesh(a6f6f570-127b-49d7-879f-f0cfddc113b1): ErrImagePull: failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout"
May 21 22:58:03 worker1 k3s[1837]: E0521 22:58:03.918377    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ErrImagePull: \"failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:58:05 worker1 k3s[1837]: E0521 22:58:05.017955    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\": dial tcp 140.82.114.33:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-coredns:v0.2.6"
May 21 22:58:05 worker1 k3s[1837]: E0521 22:58:05.018091    1837 kuberuntime_image.go:55] "Failed to pull image" err="rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\": dial tcp 140.82.114.33:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-coredns:v0.2.6"
May 21 22:58:05 worker1 k3s[1837]: E0521 22:58:05.021794    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-dns-server,Image:ghcr.io/chaos-mesh/chaos-coredns:v0.2.6,Command:[],Args:[-conf /etc/chaos-dns/Corefile],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:dns,HostPort:0,ContainerPort:5353,Protocol:UDP,HostIP:,},ContainerPort{Name:dns-tcp,HostPort:0,ContainerPort:5353,Protocol:TCP,HostIP:,},ContainerPort{Name:metrics,HostPort:0,ContainerPort:9153,Protocol:TCP,HostIP:,},ContainerPort{Name:grpc,HostPort:0,ContainerPort:9288,Protocol:TCP,HostIP:,},},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{73400320 0} {<nil>} 70Mi BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:config-volume,ReadOnly:true,MountPath:/etc/chaos-dns,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-jzkm8,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:{0 8080 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:5,TerminationGracePeriodSeconds:nil,},ReadinessProbe:&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/ready,Port:{0 8181 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,},Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[NET_BIND_SERVICE],Drop:[all],},Privileged:nil,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:*true,AllowPrivilegeEscalation:*false,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,AppArmorProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-dns-server-558955948b-9pnq4_chaos-mesh(bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887): ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\": dial tcp 140.82.114.33:443: i/o timeout"
May 21 22:58:05 worker1 k3s[1837]: E0521 22:58:05.023092    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ErrImagePull: \"rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:58:06 worker1 k3s[1837]: E0521 22:58:06.912148    1837 log.go:32] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2"
May 21 22:58:06 worker1 k3s[1837]: E0521 22:58:06.912255    1837 kuberuntime_image.go:55] "Failed to pull image" err="failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout" image="ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2"
May 21 22:58:06 worker1 k3s[1837]: E0521 22:58:06.912510    1837 kuberuntime_manager.go:1341] "Unhandled Error" err="container &Container{Name:chaos-dashboard,Image:ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2,Command:[/usr/local/bin/chaos-dashboard],Args:[],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:http,HostPort:0,ContainerPort:2333,Protocol:TCP,HostIP:,},ContainerPort{Name:metric,HostPort:0,ContainerPort:2334,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:CLEAN_SYNC_PERIOD,Value:12h,ValueFrom:nil,},EnvVar{Name:DATABASE_DATASOURCE,Value:/data/core.sqlite,ValueFrom:nil,},EnvVar{Name:DATABASE_DRIVER,Value:sqlite3,ValueFrom:nil,},EnvVar{Name:LISTEN_HOST,Value:0.0.0.0,ValueFrom:nil,},EnvVar{Name:LISTEN_PORT,Value:2333,ValueFrom:nil,},EnvVar{Name:METRIC_HOST,Value:0.0.0.0,ValueFrom:nil,},EnvVar{Name:METRIC_PORT,Value:2334,ValueFrom:nil,},EnvVar{Name:TTL_EVENT,Value:168h,ValueFrom:nil,},EnvVar{Name:TTL_EXPERIMENT,Value:336h,ValueFrom:nil,},EnvVar{Name:TTL_SCHEDULE,Value:336h,ValueFrom:nil,},EnvVar{Name:TTL_WORKFLOW,Value:336h,ValueFrom:nil,},EnvVar{Name:TZ,Value:UTC,ValueFrom:nil,},EnvVar{Name:CLUSTER_SCOPED,Value:true,ValueFrom:nil,},EnvVar{Name:TARGET_NAMESPACE,Value:chaos-mesh,ValueFrom:nil,},EnvVar{Name:ENABLE_FILTER_NAMESPACE,Value:false,ValueFrom:nil,},EnvVar{Name:SECURITY_MODE,Value:true,ValueFrom:nil,},EnvVar{Name:GCP_SECURITY_MODE,Value:false,ValueFrom:nil,},EnvVar{Name:GCP_CLIENT_ID,Value:,ValueFrom:nil,},EnvVar{Name:GCP_CLIENT_SECRET,Value:,ValueFrom:nil,},EnvVar{Name:DNS_SERVER_CREATE,Value:true,ValueFrom:nil,},EnvVar{Name:ROOT_URL,Value:http://localhost:2333,ValueFrom:nil,},EnvVar{Name:ENABLE_PROFILING,Value:true,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{25 -3} {<nil>} 25m DecimalSI},memory: {{268435456 0} {<nil>}  BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:storage-volume,ReadOnly:false,MountPath:/data,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-k4f2p,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod chaos-dashboard-5966b8f56b-m5tv9_chaos-mesh(7555d7bf-e3fd-4c73-8924-5ee983382545): ErrImagePull: failed to pull and unpack image \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to resolve reference \"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\": failed to do request: Head \"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\": dial tcp 140.82.114.33:443: i/o timeout"
May 21 22:58:06 worker1 k3s[1837]: E0521 22:58:06.914565    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ErrImagePull: \"failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:58:14 worker1 k3s[1837]: E0521 22:58:14.934890    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:58:14 worker1 k3s[1837]: E0521 22:58:14.934893    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:58:17 worker1 k3s[1837]: E0521 22:58:17.963165    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:58:17 worker1 k3s[1837]: E0521 22:58:17.966142    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:58:25 worker1 k3s[1837]: E0521 22:58:25.913038    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:58:28 worker1 k3s[1837]: E0521 22:58:28.939414    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:58:31 worker1 k3s[1837]: E0521 22:58:31.906146    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:58:31 worker1 k3s[1837]: E0521 22:58:31.906890    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:58:40 worker1 k3s[1837]: E0521 22:58:40.923759    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:58:42 worker1 k3s[1837]: E0521 22:58:42.899487    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:58:42 worker1 k3s[1837]: E0521 22:58:42.899487    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:58:45 worker1 k3s[1837]: E0521 22:58:45.929323    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:58:51 worker1 k3s[1837]: E0521 22:58:51.904467    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:58:54 worker1 k3s[1837]: E0521 22:58:54.911083    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:58:55 worker1 k3s[1837]: E0521 22:58:55.960324    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:58:56 worker1 k3s[1837]: E0521 22:58:56.902068    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:59:04 worker1 k3s[1837]: E0521 22:59:04.899347    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:59:06 worker1 k3s[1837]: E0521 22:59:06.925412    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:59:07 worker1 k3s[1837]: E0521 22:59:07.929270    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:59:10 worker1 k3s[1837]: E0521 22:59:10.931686    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:59:16 worker1 k3s[1837]: E0521 22:59:16.969499    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:59:19 worker1 k3s[1837]: E0521 22:59:19.920471    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:59:21 worker1 k3s[1837]: E0521 22:59:21.933759    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:59:22 worker1 k3s[1837]: E0521 22:59:22.959864    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:59:28 worker1 k3s[1837]: E0521 22:59:28.905020    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:59:32 worker1 k3s[1837]: E0521 22:59:32.910329    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:59:34 worker1 k3s[1837]: E0521 22:59:34.896272    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:59:37 worker1 k3s[1837]: E0521 22:59:37.930508    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:59:42 worker1 k3s[1837]: E0521 22:59:42.943796    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:59:46 worker1 k3s[1837]: E0521 22:59:46.939789    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 22:59:49 worker1 k3s[1837]: E0521 22:59:49.911727    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 22:59:52 worker1 k3s[1837]: E0521 22:59:52.930547    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 22:59:54 worker1 k3s[1837]: E0521 22:59:54.913251    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 22:59:57 worker1 k3s[1837]: E0521 22:59:57.966146    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:00:02 worker1 k3s[1837]: E0521 23:00:02.925353    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:00:06 worker1 k3s[1837]: E0521 23:00:06.913755    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:00:08 worker1 k3s[1837]: E0521 23:00:08.913412    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:00:11 worker1 k3s[1837]: E0521 23:00:11.941605    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:00:15 worker1 k3s[1837]: E0521 23:00:15.905655    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:00:18 worker1 k3s[1837]: E0521 23:00:18.919048    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:00:22 worker1 k3s[1837]: E0521 23:00:22.959794    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:00:23 worker1 k3s[1837]: E0521 23:00:23.911376    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:00:27 worker1 k3s[1837]: E0521 23:00:27.944076    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:00:31 worker1 k3s[1837]: E0521 23:00:31.911859    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:00:34 worker1 k3s[1837]: E0521 23:00:34.916825    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:00:38 worker1 k3s[1837]: E0521 23:00:38.899423    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:00:39 worker1 k3s[1837]: E0521 23:00:39.939482    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:00:42 worker1 k3s[1837]: E0521 23:00:42.912781    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:00:46 worker1 k3s[1837]: E0521 23:00:46.909418    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:00:52 worker1 k3s[1837]: E0521 23:00:52.935943    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:00:52 worker1 k3s[1837]: E0521 23:00:52.936540    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:00:55 worker1 k3s[1837]: E0521 23:00:55.907361    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:00:59 worker1 k3s[1837]: E0521 23:00:59.912705    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:01:04 worker1 k3s[1837]: E0521 23:01:04.896467    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:01:05 worker1 k3s[1837]: E0521 23:01:05.963849    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:01:06 worker1 k3s[1837]: E0521 23:01:06.907026    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:01:10 worker1 k3s[1837]: E0521 23:01:10.908672    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:01:18 worker1 k3s[1837]: E0521 23:01:18.910884    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:01:19 worker1 k3s[1837]: E0521 23:01:19.969959    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:01:20 worker1 k3s[1837]: E0521 23:01:20.916326    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:01:24 worker1 k3s[1837]: E0521 23:01:24.927834    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:01:29 worker1 k3s[1837]: E0521 23:01:29.897394    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:01:32 worker1 k3s[1837]: E0521 23:01:32.896654    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:01:32 worker1 k3s[1837]: E0521 23:01:32.896723    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:01:37 worker1 k3s[1837]: E0521 23:01:37.896092    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:01:40 worker1 k3s[1837]: E0521 23:01:40.926948    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:01:47 worker1 k3s[1837]: E0521 23:01:47.899352    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:01:47 worker1 k3s[1837]: E0521 23:01:47.901457    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:01:49 worker1 k3s[1837]: E0521 23:01:49.957963    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:01:53 worker1 k3s[1837]: E0521 23:01:53.908094    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:02:00 worker1 k3s[1837]: E0521 23:02:00.925970    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:02:01 worker1 k3s[1837]: E0521 23:02:01.898504    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:02:03 worker1 k3s[1837]: E0521 23:02:03.906054    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:02:06 worker1 k3s[1837]: E0521 23:02:06.948315    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:02:12 worker1 k3s[1837]: E0521 23:02:12.970927    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:02:13 worker1 k3s[1837]: E0521 23:02:13.896244    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:02:14 worker1 k3s[1837]: E0521 23:02:14.914752    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:02:18 worker1 k3s[1837]: E0521 23:02:18.898508    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:02:24 worker1 k3s[1837]: E0521 23:02:24.898901    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:02:24 worker1 k3s[1837]: E0521 23:02:24.899002    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:02:25 worker1 k3s[1837]: E0521 23:02:25.915967    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:02:31 worker1 k3s[1837]: E0521 23:02:31.913623    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:02:37 worker1 k3s[1837]: E0521 23:02:37.973251    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:02:37 worker1 k3s[1837]: E0521 23:02:37.974279    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:02:38 worker1 k3s[1837]: E0521 23:02:38.919982    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:02:44 worker1 k3s[1837]: E0521 23:02:44.901180    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:02:48 worker1 k3s[1837]: E0521 23:02:48.896445    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:02:50 worker1 k3s[1837]: E0521 23:02:50.905206    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-mesh\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-mesh:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-mesh/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-controller-manager-7477fb8fd9-b74v7" podUID="bc557036-fe8f-485d-9179-70bda03cb825"
May 21 23:02:51 worker1 k3s[1837]: E0521 23:02:51.934352    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
May 21 23:02:56 worker1 k3s[1837]: E0521 23:02:56.895667    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dashboard\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-dashboard:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-dashboard/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dashboard-5966b8f56b-m5tv9" podUID="7555d7bf-e3fd-4c73-8924-5ee983382545"
May 21 23:03:00 worker1 k3s[1837]: E0521 23:03:00.948865    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-dns-server\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": ErrImagePull: rpc error: code = DeadlineExceeded desc = failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-coredns:v0.2.6\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-coredns/manifests/v0.2.6\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-dns-server-558955948b-9pnq4" podUID="bfe4b1b8-40a4-4a8b-a0a9-ae1df9e5f887"
May 21 23:03:03 worker1 k3s[1837]: E0521 23:03:03.909254    1837 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"chaos-daemon\" with ImagePullBackOff: \"Back-off pulling image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": ErrImagePull: failed to pull and unpack image \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to resolve reference \\\"ghcr.io/chaos-mesh/chaos-daemon:v2.7.2\\\": failed to do request: Head \\\"https://ghcr.io/v2/chaos-mesh/chaos-daemon/manifests/v2.7.2\\\": dial tcp 140.82.114.33:443: i/o timeout\"" pod="chaos-mesh/chaos-daemon-ggxh4" podUID="a6f6f570-127b-49d7-879f-f0cfddc113b1"
